# Generated by Django 5.0.4 on 2024-04-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsubmission",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
    ]
