# Generated by Django 5.0.4 on 2024-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_examsubmission_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="keywordsList",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
