# Generated by Django 5.0.4 on 2024-05-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_examsubmissionocr"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsubmissionocr",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examsubmissionocr",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
