# Generated by Django 5.0.4 on 2024-06-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_exam_ocr_graded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsubmission",
            name="score",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name="examsubmissionocr",
            name="score",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
