# Generated by Django 5.0.4 on 2024-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_examsubmission_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsubmission",
            name="score",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="examsubmissionocr",
            name="score",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
