# Generated by Django 5.0.4 on 2024-06-30 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_examsubmissionocr_student_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsubmission",
            name="score",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(10.0)],
            ),
        ),
        migrations.AlterField(
            model_name="examsubmissionocr",
            name="score",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(10.0)],
            ),
        ),
    ]
